org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties
mod_id=dmztweaks
mod_name=DragonMineZ: Tweaks
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.iinitial.dmztweaks
mod_authors=iinitial
mod_description=This is an unofficial add-on for DragonMine Z that will tweak little things in DragonMine Z to make things more intuitive and balanced.

mixin.debug=true
mixin.debug.verbose=true
mixin.dumpTargetOnFailure=true